tailwind.config = {
        darkMode: "class",
        theme: {
          extend: {
            colors: {
              "secondary": "#5f5e58",
              "outline-variant": "#cfc4bd",
              "on-surface": "#1e1b17",
              "primary-fixed-dim": "#cdc5c0",
              "surface-container": "#f0e7df",
              "on-secondary-container": "#65645e",
              "on-error-container": "#93000a",
              "inverse-on-surface": "#f8efe8",
              "on-background": "#1e1b17",
              "error-container": "#ffdad6",
              "surface-container-low": "#f6ede5",
              "on-secondary-fixed": "#1c1c17",
              "primary": "#181512",
              "inverse-surface": "#34302b",
              "on-surface-variant": "#4d4540",
              "surface-tint": "#635d5a",
              "error": "#ba1a1a",
              "on-primary-fixed-variant": "#4b4642",
              "tertiary": "#350002",
              "surface": "#f4eee8",
              "inverse-primary": "#cdc5c0",
              "surface-variant": "#e5ddd6",
              "surface-dim": "#dcd4cd",
              "on-secondary": "#ffffff",
              "on-error": "#ffffff",
              "secondary-fixed-dim": "#c9c6bf",
              "outline": "#7e756f",
              "secondary-fixed": "#e5e2da",
              "on-secondary-fixed-variant": "#474741",
              "on-primary-container": "#96908b",
              "on-tertiary-container": "#f1625c",
              "tertiary-container": "#5c0007",
              "on-tertiary": "#ffffff",
              "primary-fixed": "#e9e1dc",
              "tertiary-fixed": "#ffdad7",
              "tertiary-fixed-dim": "#ffb3ad",
              "surface-container-lowest": "#fbf7f2",
              "on-primary": "#ffffff",
              "on-tertiary-fixed": "#410004",
              "surface-container-highest": "#e4dcd5",
              "background": "#f4eee8",
              "secondary-container": "#e5e2da",
              "primary-container": "#2d2926",
              "on-primary-fixed": "#1e1b18",
              "on-tertiary-fixed-variant": "#8b181b",
              "surface-container-high": "#e9e1da",
              "surface-bright": "#f8f1ea"
            },
            fontFamily: {
              "headline": ["Noto Serif TC", "serif"],
              "body": ["Noto Serif TC", "serif"],
              "label": ["Manrope", "Noto Sans TC", "sans-serif"]
            },
            borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
          },
        },
      }
